### PR TITLE
fix(blogposts): correct post link on tag pages

### LINKED ISSUE #118: 404 NOT FOUND
Hello,

I got the notice today that if you click in LESEZEIT on a specific tag like "mental health" you get a result of all articles tagged under the tag but you cannot open the article. It shows 404 NOT FOUND then. As you can see on the screen shot 😊
Bildschirmfoto 2022-08-24 um 20 42 22

Would you maybe have the chance to have a look into this? 🙏🏻💚

Thank you! ❤️

Bildschirmfoto 2022-08-24 um 20 42 14

### PR DESCRIPTION
**Pull request by HerrBertling**
closes #118

### CODE REVIEW

File: app/routes/$locale/blog/tag/$tag.tsx [hunk 1]
```diff
@@ -58,14 +66,7 @@ export default function Index() {
...
   const caught = useCatch();
-  return (
-    <div className="container mx-auto mt-32">
-      <h2>Oh noez! We failed.</h2>
-      <p>
-        {caught.status}: {caught.statusText}
-      </p>
-    </div>
-  );
+  return <BasicCatchBoundary {...caught} />;
```
Comment (NoeliaEle) [inline app/routes/$locale/blog/tag/$tag.tsx:69]: Love the new emoji-errors :D Could we use `<BasicCatchBoundary/>` in the other places where we also display such a message?

Screenshot 2022-09-02 at 09 15 26

Comment (NoeliaEle) [inline app/routes/$locale/blog/tag/$tag.tsx:69]: Love the new emoji-errors :D Could we use `<BasicCatchBoundary/>` in the other places where we also display such a message?

Screenshot 2022-09-02 at 09 15 26

File: app/components/BasicCatchBoundary.tsx [hunk 2]
```diff
@@ -8,9 +8,9 @@ export default function BasicCatchBoundary({
...
     <div className="mx-auto min-h-[50vh] w-screen max-w-3xl px-4 pt-32 pb-12">
       <div className="prose prose-lg prose-slate lg:prose-xl">
-        <h2>Oh no! A {status} error!</h2>
-        {status === 404 && <p>We couldn't find that page!</p>}
-        <p>This is what the machines tell us:</p>
+        <h2>Oh no! A {status} error! 🙀</h2>
+        {status === 404 && <p>We couldn't find that page! 😬</p>}
+        <p>This is what the machines tell us 🤖</p>
         <pre className="bg-slate-700">
           <code>{statusText}</code>
```
Comment (NoeliaEle) [inline app/components/BasicCatchBoundary.tsx:15]: Screenshot 2022-09-02 at 09 18 10

Should we display the `This is what the machine tell us....` only if we have statusText? Otherwise the text looks a bit broken. Maybe just display a default "Try again later" if we don't have statusText

File: app/routes/$locale/blog/tag/$tag.tsx (hunk 1 above)
Comment (NoeliaEle) [inline app/routes/$locale/blog/tag/$tag.tsx:69]: Love the new emoji-errors :D Could we use `<BasicCatchBoundary/>` in the other places where we also display such a message?

Screenshot 2022-09-02 at 09 15 26

**Review by NoeliaEle — APPROVED** [review]
Overall looks good! Just minor clean-ups 🚀 🥳

File: app/components/BasicCatchBoundary.tsx (hunk 2 above)
Comment (HerrBertling) [reply app/components/BasicCatchBoundary.tsx:15]: Oh, yes! Will change that.
